name: Deploy Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install fpm
        id: install_fpm
        continue-on-error: true
        uses: actions-rs/cargo@v1
        with:
            command: install
            args: fpm
      