name: Deploy Site

on:
  push:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout build branch
        uses: actions/checkout@v2
        with:
          ref: build
          path: build
      - name: Install fpm
        id: install_fpm
        continue-on-error: false
        uses: actions-rs/cargo@v1
        working-directory: ./main
        with:
          command: install
          args: fpm
      - name: Build the pages with fpm
        id: build
        continue-on-error: false
        run: fpm build
        working-directory: ./main
      - name: Clear the previous build
        id: clear-previous-build
        continue-on-error: false
        run: rm -rf *
        working-directory: ./build
      - name: Move the build directory
        id: move
        continue-on-error: false
        run: mv .build/* ../build/
        working-directory: ./main
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit changes to build branch
        with:
          commit_message: SSR build
          branch: build
          commit_options: '--no-verify --signoff'
          file_pattern: docs/*
          repository: .